name: Clojure CI

on:
  push:
    branches: [ "master", "devel" ]
  pull_request:
    branches: [ "master", "devel" ]

jobs:
  #############################################
  ## Build
  #############################################
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 21

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@13.2
      with:
        cli: 1.11.4.1474
        lein: 2.11.2
        cljfmt: latest

    - name: Install dependencies
      run: lein -U deps

    - name: Run tests
      run: lein test
  #############################################
  ## Clojars
  #############################################
  clojars:
    runs-on: ubuntu-latest
    needs: build
    - name: Deploy to Clojars
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/devel'
      run: lein deploy
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
  #############################################
  ## Marginalia
  #############################################
  marginalia:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Generate documentation
        if: github.ref == 'refs/heads/master'
        run: lein marg -d public -f index.html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
